### ISSUE TITLE
Features to implement

### ISSUE THREAD

**Issue by gdbarron** [gdbarron/VenafiTppPS#1]
Hi all.  I'm interested in implementing features which will be most useful to folks.  Please let me know your thoughts!  The SDK can be found  [https://docs.venafi.com/Docs/18.1SDK/TopNav/Content/SDK/WebSDK/API_Reference/c-REST-API-reference.php?tocpath=REST%20API%20reference%7C_____0](here).

@BeardedPrincess, mind chiming in?

**Comment by wilddev65** [comment]
I'll add a couple I've used as well;
**Get-TPPObjectClass**
- Uses Config/FindObjectsOfClass to find objects of a specific class and return the DN
**Test-CSVFile**
- A generic test to see if a CSV has the correct columns and has rows for bulk operations

**Comment by gdbarron** [comment]
Thanks, @wilddev65!  I've added an issue for Get-TppConfigObject, #11.

**Comment by gdbarron** [comment]
@wilddev65, I've added Get-TppObject which allows you to get an object either by class or pattern.

**Comment by Saadi6** [comment]
@gdbarron Thank you for adding Get-TppPermission. 

I think a function for setting permissions should incorporate few checks to prevent unintentional changes because the level of access a user has to objects in TPP underpins the functions they can perform in the GUI. 

This may be split into two or more functions for better usability. 

**Set-TppPermission**
Sets new or updates existing permission on an object while considering the following:

- Uses POST Permissions to set new permissions when explicit permissions on the object for _this_ identity does not exist.
- Uses PUT Permissions to update permissions when explicit permissions on the object for _this_ identity exists.
- A switch indicates whether all existing explicit permissions for _this_ identity are removed before setting new permissions. This calls another function to delete permissions for _this_ identity when they exist. 
- Implicit (inherited) IsManagePermissionsAllowed is not over ridden by a lesser explicit permission for _this_ identity unless confirmed with a switch.
- If _this_ identity already has any implicit (inherited) permission on _this_ object then a switch confirms explicit permissions should be set anyway.
- Parse the set of permission strings to ensure they match names in TPP documentation.

**Comment by mlamutt** [comment]
Hi all, 
First off, thanks for this great module.  There are a lot of good functions here.  I am looking to add a disassociate a certificate from an application, and a delete certificate function.  Does any of the existing functions cover these 2 requests?  If not it looks like it would be fairly straight forward to adding them.  

https://docs.venafi.com/Docs/18.2SDK/TopNav/Content/SDK/WebSDK/API_Reference/r-SDK-POST-Certificates-Dissociate.php?Highlight=remove%20from%20application

https://docs.venafi.com/Docs/18.2SDK/TopNav/Content/SDK/WebSDK/API_Reference/r-SDK-DELETE-Certificates-Guid.php?Highlight=delete%20certificate

thanks

**Comment by Saadi6** [comment]
Delete Certificates/{guid} is a little heavy handed if all you wish to do is remove application and device association from a certificate. Use the Certificates/Dissociate for this purpose. This method allows you to optionally remove the device and application objects if they have been orphaned i.e. the same device object is not associated with another certificate. 

If a Delete Certificate function is added then a Dissociate Certificate function should also be added at the same time. Delete function may have an additional safety to check for an association. A switch confirms certificate objects with associations should be deleted.  

Note that neither Delete nor Dissociate method removes the Device object if it has other associations, which is handy. 

cheers.

**Comment by mlamutt** [comment]
@Saadi6  I agree with all your statements.  The Delete Certificate is for a specific use case,  in our case a website has been decommissioned, and we are purging the full config, from the code base, load balancer config, cert , etc..  In most cases we move the cert to an archive folder that is not monitored after it has been dissociated from all applications.

**Comment by gdbarron** [comment]
Thanks guys.  I'm working on finalizing permission updates and then will have a look at dissociate and delete cert.  @mlamutt, would you mind creating a new issue for this?

**Comment by tristanbarcelon** [comment]
@gdbarron , first off, thank you for this very useful module. I've been using it to obtain metadata about our certs in Venafi, but lately I have a need to actually download the certificate file (in pem or pfx) to the file system. My plan is to use this download feature to fetch a code signing or an SSL cert during build or deployment from Venafi, install it on the target, and then wipe the file. Would you be open to a PR which uses the /vedsdk/certificates/Retrieve endpoint to download the certificate file by using its distinguished name?

**Comment by Saadi6** [comment]
@tristanbarcelon suggested function is useful. 

Certificate/Retrieve will return the X.509 certificate on its own or with a Private Key if present in TPP. Including private key forces use of a password. Instead of generating a password in your function, I suggest making it a mandatory parameter when private key is to be included - same as how Certificate/Retrieve works. The password for the private key should not touch disk in clear text.  

Certificate/Retrieve supports the most common containers such as JKS, PKCS or raw cert data. 

As an aside - it does not support KeePass, which is commonly used by IBM's applications. I believe IBM uses v1 of KeePass which has KDB file extension. I baked on support for KDB by retrieving in PKCS format from Certificate/Retrieve then converting to KDB using a utility from IBM's GSKit. The function then emails the KDB or writes it do disk and returns its location. GSKit is proprietary but I came across this recently https://github.com/PSKeePass/PoShKeePass. Might be worth looking into for future...

Regards.

**Comment by gdbarron** [comment]
@tristanbarcelon, thanks for your suggestion and as @Saadi6 says it will definitely be useful.  What good is a certificate management module if you can't get a cert? :)  I'm definitely open to you working on this.  Can you please create a new Issue for this enhancement and assign it to yourself?

There shouldn't be any issues with using Invoke-TppRestMethod as is...I don't think.  I've put [a sample](https://github.com/gdbarron/VenafiTppPS/blob/get-cert-sample/VenafiTppPS/Code/Public/Get-TppCertificate.ps1) in a new branch for you to have a look.  It doesn't use `-OutFile`, but rather does a base64 conversion of the certificate data.

**Comment by gdbarron** [comment]
Most of the suggestions here have been implemented.  Any new enhancements can be entered as a new issue.
