### ISSUE TITLE
Problem with WriteTppLog

### ISSUE THREAD

**Issue by stevekeever** [gdbarron/VenafiTppPS#114]
# Environment

```
Operating System: Windows 10
VenafiTppPS version: 20.2.0.5474
PowerShell version: 5.1.18362.752 
```

# Steps to reproduce

Please see the attached script.  When I utilize your wrapper with an API Key, the log is written.  However, when I use an OAuth token, I get this error:

![WriteLogError](https://user-images.githubusercontent.com/70722151/92160577-16db0400-ede4-11ea-99b4-b15688d47a58.jpg)

Otherwise - Just a shout out.  Your code saves me HOURS!!!  Thanks for taking a look.

[Create Log Event-OAuth and APIKey.ps1.txt](https://github.com/gdbarron/VenafiTppPS/files/5170856/Create.Log.Event-OAuth.and.APIKey.ps1.txt)

**Comment by gdbarron** [comment]
Hi @stevekeever, thanks for reporting this.  This is due to a missing trailing slash in the url.  Some of us went back and forth on how to implement this best back when v2.0 with token-based auth was released and ended up with https://github.com/gdbarron/VenafiTppPS/issues/94#issuecomment-635731101.  It looked like it was only needed for Gets, but I'll have to update to include others.  I'll try and have an update out in the next few days.

Glad to hear how much time the module is saving you.  Hours is a good start, let me know what can be included to save you **days** 😄 

FYI @BeardedPrincess @Saadi6

**Comment by stevekeever** [comment]
I may not be doing it correctly, but it appears that Invoke-RestMethod is still purging the header on a POST even with the trailing slash.  :(  

![WriteLogError2](https://user-images.githubusercontent.com/70722151/92245230-e2655780-ee78-11ea-9617-0262dbcdf00c.jpg)

Works just peachy in Postman.

**Comment by Saadi6** [comment]
@stevekeever trailing slash appears to do the trick here.

@gdbarron there is additional info at https://docs.venafi.com/Docs/20.2SDK/TopNav/Content/SDK/WebSDK/r-SDK-POST-Log.php around why this method should include a trailing slash.

**Comment by gdbarron** [comment]
@Saadi6, thanks for the info.  I thought we had originally discussed this only being an issue with Get so was surprised to see it on a Post and wanted to give you the heads up.  All fixed now.

**Comment by Saadi6** [comment]
@gdbarron, from documentation this appears to have changed since v20.1. While I don't believe all other POST methods now require trailing slash from PowerShell, this might be something you have to watch-out for in the future.

**Comment by gdbarron** [comment]
I've updated the error handling to try with a trailing slash for all methods, not just Get, so we should be covered.
