### ISSUE TITLE
hostname?

### ISSUE THREAD

**Issue by Curtmcgirt** [gdbarron/VenafiTppPS#130]
the venafi gui field for creating new devices is "hostname/ip address", but the new-tppdevice cmdlet has an -ipaddress switch that doesn't like FQDNs on account of FQDNs not being ip addresses. is there an alternate way to create new devices with FQDNs instead of ip addresses?

**Comment by gdbarron** [comment]
Yep, looks to be a gap I'll have to put in an enhancement for.  Thanks for pointing this out.

There is an alternate way, `New-TppObject -Path '\ved\policy\mypath\mydevice' -class 'device' -Attribute @{'host'='me.domain.com'}`

**Comment by Curtmcgirt** [comment]
on new-tppobject, would i need to add multiple attributes  for the -credentialpath and -devicename that new-tppdevice has but new-tppobject does not??

i found that creating the device without an IP address and them immediately set-tppattribue for 'host' works. i just have to assemble the path to the new device. i'd be cool if i could $myvariable = new-tppdevice blah blah blah and when it was finished, $myvariable would have attibutes about the new device i just created ($myvariable.path would be its path)

**Comment by gdbarron** [comment]
Yep, you'll need to add all the attributes that `New-TppDevice` provides if you need them.  Credential path would be `@{'Credential'='PathToCredObject'}`.  Device name can be part of the path if you only need to create one device, eg. \ved\policy\thisfolder\mydevice.  The benefit to providing device name separately as `-DeviceName` is if you wanted to create multiple devices at once and provide a list of names.  In that case, the path would be to the policy folder instead of policy folder + device name.  But, that doesn't help you much if you need to provide hostname at the same time.

`New-TppDevice` can return the new TppObject, simply add `-PassThru` to the call.

**Comment by gdbarron** [comment]
Keep in mind, you can pipe `New-TppDevice -PassThru` to `Set-TppAttribute` to set the host without even the need for $myvariable...if you want.
