### ISSUE TITLE
API Session Timeout (Test-TPPSession)

### ISSUE THREAD

**Issue by BeardedPrincess** [gdbarron/VenafiTppPS#3]
It seems the current implementation is using the ValidUntil value returned from the New-TPPSession to track how long the API key is valid for. This seems ok on the surface, but has a slight issue.

The ValidUntil is really more of a session-timeout. The API key is valid for 3 minutes. Every time a successful API query is made against TPP, the session ValidUntil gets reset to 3 minutes. So, checking the original ValidUntil may result in a re-authentication to TPP when one isn't necessary.  (And authentication can be a pretty expensive operation on the TPP side, and should be minimized)

I'd recommend a couple of options. The first would be just to ignore the ValidUntil, and simply trap the specific error that will get thrown when the session times out inside of Invoke-TPPRestMethod. If the error is that the API key is invalid, simply re-auth at that point.  The other option would be to update the ValidUntil inside Invoke-TPPRestMethod by calculating 150 seconds from now. (This is less than the 180 seconds that TPP will set, but gives a bit of buffer for timing etc.)

**Comment by gdbarron** [comment]
Very helpful stuff.  I just re-read the SDK and must have missed the re-up originally.

Putting re-auth in Invoke-TppRestMethod would work for some scenarios, but not all.  For instance, if we pipe 1000 objects and it's been over 3 minutes since our last call, we would re-auth 1000 times.  We could always reset TppSession to the script level variable at the top of the process loop, but this might incur a performance hit and would preclude us from using any sort of parallelism.

I definitely want to get this component solid as all other functions will rely on it :)  Let me give this some additional thought and come back to you with suggestions.

**Comment by gdbarron** [comment]
Here's the PR, #4 .  I thought it best to perform the validation up front to alleviate the issues mentioned above.  The connect and validation is now being done in a TppSession class.  Please have a look when you get a chance.

**Comment by BeardedPrincess** [comment]
I like the approach of the Validate method on the class. Here are a couple more ideas:

- Move the call to session.Validate() into the Invoke-TPPRequest function. Then you won't need to remember to put it into all the new functions you're creating.

- The POST /authorize/checkvalid returns a new 'ValidUntil' time stamp. In the validate function, if you first checked the ValidUntil property, and only if it's expired called checkvalid (and use it's result to update ValidUntil for next time), you'd only end up calling checkvalid at max once every 3-minutes.  Then, if your script makes 2000 config/writes, but they're all done in 3 minutes, you won't end up calling checkvalid 2000 times too.

**Comment by gdbarron** [comment]
Thanks for the feedback.  For your first bullet, unless I'm missing something, I think the same issue exists as before.  I definite like the idea of having Validate in only one place, but if I move it and it needs to re-auth, I need to pass that new session back out of Invoke-TppRequest otherwise all other calls in the pipeline will fail.  Please let me know where my logic is wrong....

For the second bullet, great idea, will definitely implement.

**Comment by BeardedPrincess** [comment]
You're right.. I missed that the functions were setup to accept pipeline input. This is looking great!

**Comment by gdbarron** [comment]
I'm sure we could enhance this even further by tracking the time as you mentioned earlier, but we'll look to that in a future release :)
